### ISSUE TITLE
quickstart #3

### ISSUE THREAD

**Issue by fitbodylife** [stormpath/stormpath-sdk-php#22] opened 2015-02-01 09:35 UTC
where do i list all the directories and files in step #4 of your quickstart

**Comment by omgitstom** [comment] 2015-02-04 20:47
Hi @fitbodylife 

I don't understand your question - can you elaborate?

Thanks!
Tom

**Comment by fireproofsocks** [comment] 2015-03-24 01:24
I'm confused as well -- in the readme, where on earth are the $applicationHref and $directoryHref variables coming from?  What are they supposed to contain?

````
$application = \Stormpath\Resource\Application::get($applicationHref);
$directory = \Stormpath\Resource\Directory::get($directoryHref);
````

**Comment by omgitstom** [comment] 2015-03-24 01:41
Hi @fireproofsocks,

It might be easier to follow http://docs.stormpath.com/php/quickstart/

The applicationHref / directoryHref can either be hardcoded (retrieved from the Stormpath Administrator Console) or can be retrieved via code.  When you iterate over the object (step 3 in the README.md) you can output the href for the individual objects for the href (app->href)

If you are in the administrator console, click on the applications or directories tab, once you click on an individual application / directory, the href will be in the Details pane.

Hope this helps!

**Comment by bretterer** [comment] 2015-05-27 03:32
@fireproofsocks Did the above help you?  Is there anything else we can clarify for you?

**Comment by fireproofsocks** [comment] 2015-05-27 05:16
@bretterer: no, unfortunately it doesn't really help -- the problem is that each set of docs is incomplete.  The github readme has some fragments, the docs.stormpath.com pages have others.  It's not necessary to be verbose in docs, but thoroughness is essential, otherwise devs are required to spend a lot of time grunting through source code.  I would consider this issue resolved if there were a complete example demonstrating both input and output, e.g. if the clarifications mentioned by @omgitstom were included in the README.md in the form of sample code.

Relatedly, it would be nice to omit words/phrases such as "simple", "etc." and any time there's a list of tantalizing bits of functionality (e.g. "Other Things You Can Do with Stormpath"), then docs really are the proper place to actually *show* how to do those things instead of just talk about them.

**Comment by ecrisostomo** [comment] 2015-07-14 21:24
Documentation added on 1.6.0.beta.

**Closed by ecrisostomo** 2015-07-14 21:24 UTC
